export type CatalogMovie = {
  slug: string;
  title: string;
  imageUrl: string;
  backdropUrl: string;
  description: string;
  durationMin: number;
  genres: string[];
  language: string;
  certification: string;
  formats: string[];
  cast: string[];
  director: string;
  status: 'now-showing' | 'coming-soon';
  releaseDate: string;
  featured: boolean;
  rating: number;
  inrPrice: number;
};

export const catalog: CatalogMovie[] = [
  {
    slug: 'jawan',
    title: 'Jawan',
    imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=800',
    backdropUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=1600',
    description:
      'A high-octane action thriller that follows a man who is driven by a personal vendetta to rectify the wrongs in society, with intense stunts and a dual-role spectacle.',
    durationMin: 169,
    genres: ['Action', 'Thriller'],
    language: 'Hindi',
    certification: 'UA',
    formats: ['2D', 'IMAX'],
    cast: ['Shah Rukh Khan', 'Nayanthara', 'Vijay Sethupathi'],
    director: 'Atlee',
    status: 'now-showing',
    releaseDate: '2023-09-07',
    featured: true,
    rating: 8.2,
    inrPrice: 280,
  },
  {
    slug: 'rrr',
    title: 'RRR',
    imageUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80&w=800',
    backdropUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&q=80&w=1600',
    description:
      'A fictional story about two legendary revolutionaries and their journey away from home before they started fighting for their country in the 1920s.',
    durationMin: 187,
    genres: ['Action', 'Drama'],
    language: 'Telugu',
    certification: 'UA',
    formats: ['2D', '3D', 'IMAX'],
    cast: ['N. T. Rama Rao Jr.', 'Ram Charan', 'Alia Bhatt'],
    director: 'S. S. Rajamouli',
    status: 'now-showing',
    releaseDate: '2022-03-24',
    featured: true,
    rating: 8.8,
    inrPrice: 320,
  },
  {
    slug: '12th-fail',
    title: '12th Fail',
    imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=800',
    backdropUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=1600',
    description:
      'The real-life story of an IPS officer who overcame extreme poverty and repeated failure to crack one of India’s toughest examinations.',
    durationMin: 147,
    genres: ['Drama', 'Biography'],
    language: 'Hindi',
    certification: 'U',
    formats: ['2D'],
    cast: ['Vikrant Massey', 'Medha Shankar'],
    director: 'Vidhu Vinod Chopra',
    status: 'now-showing',
    releaseDate: '2023-10-27',
    featured: false,
    rating: 9.1,
    inrPrice: 220,
  },
  {
    slug: 'inception',
    title: 'Inception',
    imageUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&q=80&w=800',
    backdropUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?auto=format&fit=crop&q=80&w=1600',
    description:
      'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    durationMin: 148,
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    language: 'English',
    certification: 'UA',
    formats: ['2D', 'IMAX'],
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    director: 'Christopher Nolan',
    status: 'now-showing',
    releaseDate: '2010-07-16',
    featured: true,
    rating: 8.8,
    inrPrice: 350,
  },
  {
    slug: 'interstellar',
    title: 'Interstellar',
    imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&q=80&w=800',
    backdropUrl: 'https://images.unsplash.com/photo-1464802686167-b339d62d0c40?auto=format&fit=crop&q=80&w=1600',
    description:
      'A team of explorers travel through a wormhole in space in an attempt to ensure humanity’s survival.',
    durationMin: 169,
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    language: 'English',
    certification: 'UA',
    formats: ['2D', 'IMAX'],
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    director: 'Christopher Nolan',
    status: 'now-showing',
    releaseDate: '2014-11-07',
    featured: true,
    rating: 8.7,
    inrPrice: 380,
  },
  {
    slug: 'dangal',
    title: 'Dangal',
    imageUrl: 'https://images.unsplash.com/photo-1552072092-7f9b8d63efcb?auto=format&fit=crop&q=80&w=800',
    backdropUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba6851?auto=format&fit=crop&q=80&w=1600',
    description:
      'Former wrestler Mahavir Singh Phogat trains his daughters to become world-class wrestlers.',
    durationMin: 161,
    genres: ['Biography', 'Drama', 'Sport'],
    language: 'Hindi',
    certification: 'U',
    formats: ['2D'],
    cast: ['Aamir Khan', 'Fatima Sana Shaikh', 'Sanya Malhotra'],
    director: 'Nitesh Tiwari',
    status: 'now-showing',
    releaseDate: '2016-12-23',
    featured: false,
    rating: 8.4,
    inrPrice: 250,
  },
  {
    slug: 'the-dark-knight',
    title: 'The Dark Knight',
    imageUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?auto=format&fit=crop&q=80&w=800',
    backdropUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&q=80&w=1600',
    description:
      'When the Joker wreaks havoc on Gotham, Batman must accept one of the greatest tests of his ability to fight injustice.',
    durationMin: 152,
    genres: ['Action', 'Crime', 'Drama'],
    language: 'English',
    certification: 'UA',
    formats: ['2D', 'IMAX'],
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    director: 'Christopher Nolan',
    status: 'now-showing',
    releaseDate: '2008-07-18',
    featured: false,
    rating: 9.0,
    inrPrice: 340,
  },
  {
    slug: '3-idiots',
    title: '3 Idiots',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=800',
    backdropUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=1600',
    description:
      'Two friends search for their long-lost college companion while flashbacks reveal how he challenged a pressure-cooker education system.',
    durationMin: 170,
    genres: ['Comedy', 'Drama'],
    language: 'Hindi',
    certification: 'UA',
    formats: ['2D'],
    cast: ['Aamir Khan', 'R. Madhavan', 'Sharman Joshi'],
    director: 'Rajkumar Hirani',
    status: 'now-showing',
    releaseDate: '2009-12-25',
    featured: false,
    rating: 8.4,
    inrPrice: 230,
  },
  {
    slug: 'pathaan',
    title: 'Pathaan',
    imageUrl: 'https://images.unsplash.com/photo-1594908900066-3f47337549d8?auto=format&fit=crop&q=80&w=800',
    backdropUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&q=80&w=1600',
    description:
      'An exiled RAW agent must stop a mercenary organization from launching a deadly attack on India.',
    durationMin: 146,
    genres: ['Action', 'Thriller'],
    language: 'Hindi',
    certification: 'UA',
    formats: ['2D', 'IMAX'],
    cast: ['Shah Rukh Khan', 'Deepika Padukone', 'John Abraham'],
    director: 'Siddharth Anand',
    status: 'now-showing',
    releaseDate: '2023-01-25',
    featured: false,
    rating: 7.9,
    inrPrice: 300,
  },
  {
    slug: 'spider-verse',
    title: 'Spider-Man: Across the Spider-Verse',
    imageUrl: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&q=80&w=800',
    backdropUrl: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?auto=format&fit=crop&q=80&w=1600',
    description:
      'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
    durationMin: 140,
    genres: ['Animation', 'Action', 'Adventure'],
    language: 'English',
    certification: 'U',
    formats: ['2D', '3D', 'IMAX'],
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac'],
    director: 'Joaquim Dos Santos',
    status: 'now-showing',
    releaseDate: '2023-06-02',
    featured: true,
    rating: 8.6,
    inrPrice: 360,
  },
  {
    slug: 'kalki-2898-ad',
    title: 'Kalki 2898 AD',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800',
    backdropUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&q=80&w=1600',
    description:
      'A mythic sci-fi epic set in a future dystopia where rebels fight to protect the unborn child believed to be Kalki.',
    durationMin: 181,
    genres: ['Sci-Fi', 'Action', 'Fantasy'],
    language: 'Telugu',
    certification: 'UA',
    formats: ['2D', 'IMAX'],
    cast: ['Prabhas', 'Deepika Padukone', 'Amitabh Bachchan'],
    director: 'Nag Ashwin',
    status: 'coming-soon',
    releaseDate: '2026-09-18',
    featured: false,
    rating: 8.0,
    inrPrice: 400,
  },
  {
    slug: 'dune-part-three',
    title: 'Dune: Part Three',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&q=80&w=800',
    backdropUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&q=80&w=1600',
    description:
      'The desert planet’s fate hangs in the balance as Paul Atreides walks the line between messiah and tyrant.',
    durationMin: 166,
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    language: 'English',
    certification: 'UA',
    formats: ['2D', 'IMAX'],
    cast: ['Timothée Chalamet', 'Zendaya', 'Florence Pugh'],
    director: 'Denis Villeneuve',
    status: 'coming-soon',
    releaseDate: '2026-12-18',
    featured: false,
    rating: 8.5,
    inrPrice: 420,
  },
];
